In [1]:
import pandas as pd
from huggingface_hub import hf_hub_download

In [2]:
train_path = hf_hub_download(repo_id = "Cleanlab/stanford-politeness", filename = "fine-tuning/train_full.csv", repo_type = "dataset")
test_path = hf_hub_download(repo_id = "Cleanlab/stanford-politeness", filename = "fine-tuning/test.csv", repo_type = "dataset")

In [3]:
train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

In [4]:
train_df.head(10)

,text,a1,a2,a3,a4,a5,a6,a7,a8,a9,...,a214,a215,a216,a217,a218,a219,label,label_cat,label_noisy,label_cat_noisy
0,Question: how do we move the content from the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,neutral,1,neutral
1,Why would you doubt that. And for that matter ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,impolite,0,impolite
2,Thank you for closing out this debate. Can yo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2,polite,1,neutral
3,You may want to take a look at <url>. Can you...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,neutral,1,neutral
4,The consequences apparently have no sliding sc...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,impolite,0,impolite
5,"Good! By the way, what do you think of merging...",NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,neutral,2,polite
6,You didn't answer about the status of above me...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,impolite,2,polite
7,"Please take a look at Space Shuttle Discovery,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2,polite,2,polite
8,"Hi, Schutz; it's still busted. Would it be OK...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,neutral,2,polite
9,The deletion review page linked above contains...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,impolite,1,neutral

In [5]:
test_df.head()

                                              prompt completion
0      Excuse me? What are you accusing me of doing?   impolite
1                         I don't understand Tasc0??   impolite
2  Well, you leaved me also curious. Why was it n...   impolite
3  Hi, I meant to do this a long time ago, but I ...    neutral
4  DONE. Do you think everything is now sorted so...    neutral

In [6]:
train_df = train_df[["text", "label_cat", "label"]].dropna()

In [7]:
train_df.head()

                                                text label_cat  label
0  Question: how do we move the content from the ...   neutral      1
1  Why would you doubt that. And for that matter ...  impolite      0
2  Thank you for closing out this debate.  Can yo...    polite      2
3  You may want to take a look at <url>.  Can you...   neutral      1
4  The consequences apparently have no sliding sc...  impolite      0

In [8]:
label2id = {"impolite": 0, "neutral": 1, "polite": 2}
id2label = {v: k for k, v in label2id.items()}

test_df = test_df[["prompt", "completion"]].dropna()
test_df = test_df.rename(columns={"prompt": "text", "completion": "label_cat"})
test_df["label"] = test_df["label_cat"].map(label2id)

In [9]:
test_df.head()

                                                text label_cat  label
0      Excuse me? What are you accusing me of doing?  impolite      0
1                         I don't understand Tasc0??  impolite      0
2  Well, you leaved me also curious. Why was it n...  impolite      0
3  Hi, I meant to do this a long time ago, but I ...   neutral      1
4  DONE. Do you think everything is now sorted so...   neutral      1

In [10]:
print(train_df["label_cat"].value_counts())
print(train_df["label_cat"].value_counts(normalize=True))

print(test_df["label_cat"].value_counts())
print(test_df["label_cat"].value_counts(normalize=True))

label_cat
neutral     865
impolite    689
polite      362
Name: count, dtype: int64
label_cat
neutral     0.451461
impolite    0.359603
polite      0.188935
Name: proportion, dtype: float64
label_cat
neutral     216
impolite    173
polite       91
Name: count, dtype: int64
label_cat
neutral     0.450000
impolite    0.360417
polite      0.189583
Name: proportion, dtype: float64

In [11]:
device = "cuda"

In [12]:
import torch

In [13]:
class_counts = train_df["label"].value_counts().sort_index()

In [14]:
total = class_counts.sum()

In [15]:
num_classes = len(class_counts)

In [16]:
class_weights = total / (class_counts * num_classes)
class_weights = torch.tensor(class_weights.values, dtype=torch.float)

print(class_counts)
print(class_weights)

label
0    689
1    865
2    362
Name: count, dtype: int64
tensor([0.9269, 0.7383, 1.7643])

In [17]:
from transformers import Trainer

In [18]:
import torch.nn as nn

In [19]:
class WeightedTrainer(Trainer):
  def compute_loss(self, model, inputs, return_outputs = False, **kwargs):
    labels = inputs.pop("labels")
    outputs = model(**inputs)
    logits = outputs.logits
    loss_fct = nn.CrossEntropyLoss(weight = class_weights)
    loss = loss_fct(logits.view(-1, num_classes), labels.view(-1))
    return (loss, outputs) if return_outputs else loss

In [20]:
from transformers import AutoTokenizer
from datasets import Dataset

tokenizer = AutoTokenizer.from_pretrained("roberta-base")

train_ds = Dataset.from_pandas(train_df[["text", "label"]])
test_ds = Dataset.from_pandas(test_df[["text", "label"]])

lengths = train_df["text"].apply(lambda x: len(tokenizer.encode(x)))
print(lengths.describe())

count    1916.000000
mean       34.501566
std        18.308054
min         3.000000
25%        22.000000
50%        30.000000
75%        43.000000
max       179.000000
Name: text, dtype: float64

In [21]:
print((lengths > 64).mean())

0.06210855949895616

In [22]:
def tokenize_fn(example):
  tokenized = tokenizer(example["text"], truncation = True, padding = "max_length", max_length = 64)
  tokenized["labels"] = example["label"]
  return tokenized

train_ds = train_ds.map(tokenize_fn, batched=True)
test_ds = test_ds.map(tokenize_fn, batched=True)

train_ds.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])
test_ds.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

Map:   0%|          | 0/1916 [00:00<?, ? examples/s]

Map:   0%|          | 0/480 [00:00<?, ? examples/s]

In [44]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "roberta-base",
    num_labels = 3,
    id2label=id2label,
    label2id=label2id,
)

model = model.to(device)
class_weights = class_weights.to(device)

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [45]:
from transformers import TrainingArguments

from google.colab import drive
drive.mount('/content/drive')

training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/paraphrase-tool/checkpoints/politeness-classifier-v3",
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=4,
    learning_rate=2e-5,
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=4,
    logging_steps=20,
    load_best_model_at_end=True,
    metric_for_best_model="eval_accuracy",
    report_to="none",
)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [25]:
import numpy as np
from sklearn.metrics import precision_recall_fscore_support, accuracy_score

In [31]:
def compute_metrics(eval_pred):
  logits, labels = eval_pred
  preds = np.argmax(logits, axis = -1)

  p, r, f1, _ = precision_recall_fscore_support(labels, preds, average = None, labels = [1,0,2])
  acc = accuracy_score(labels, preds)
  metrics = {"accuracy" : acc}

  for i, class_name in id2label.items():
      metrics[f"f1_{class_name}"] = f1[i]
      metrics[f"precision_{class_name}"] = p[i]
      metrics[f"recall_{class_name}"] = r[i]

  return metrics

In [27]:
!pip install -U datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.20.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)

In [46]:
trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=test_ds,
    compute_metrics=compute_metrics,
)

trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=240, training_loss=0.6728134075800578, metrics={'train_runtime': 140.7655, 'train_samples_per_second': 54.445, 'train_steps_per_second': 1.705, 'total_flos': 252062654183424.0, 'train_loss': 0.6728134075800578, 'epoch': 4.0})

In [47]:
trainer.save_model("/content/drive/MyDrive/paraphrase-tool/checkpoints/politeness-classifier-v3/final")
tokenizer.save_pretrained("/content/drive/MyDrive/paraphrase-tool/checkpoints/politeness-classifier-v3/final")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('/content/drive/MyDrive/paraphrase-tool/checkpoints/politeness-classifier-v3/final/tokenizer_config.json',
 '/content/drive/MyDrive/paraphrase-tool/checkpoints/politeness-classifier-v3/final/tokenizer.json')